### ISSUE TITLE
create MVIF n. 5 conference on openreview

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/openreviewr#2]
I'd like to start using the API to create new submission sites, so we can e.g. create the next 6 months worth easily. I'd also like to document it so that someone without programming expertise could modify the templates and run. I've made first steps towards a template in https://github.com/waldronlab/openreviewr/tree/main/inst/scripts, trying to simplify our current structure by not having year, only MicrobiomeVIF/n5, etc, but not sure if this is allowed. 

@jwokaty could you help get this script working, and talk with the openreview support people as needed? The documentation this is based on is https://openreview-py.readthedocs.io/en/latest/conference_builder.html. We are supposed to open n. 5 for submissions on Nov 9, although that could be pushed back a bit, or we could do the next one instead by support request as we have the previous ones, if that's not realistic.

**Comment by jwokaty** [comment]
I requested the support for the new submission site on OpenReview since we want to open for submissions 11/9. To create via the API, the user need to be an admin. I'll continue to work on the conference creator.

**Comment by jwokaty** [comment]
Closing since the script is working.
